# Generated by Django 4.2.6 on 2023-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_by',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
